
title: KI Sommerschule 
logo: logo.jpeg
description: Gemeinsame KI Sommerschule der Hochschulen Offenburg und Karlsruhe. Kontakt -> info@ki-sommer.de 
show_downloads: false
theme: jekyll-theme-minimal
